import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-10`}
      >
        <header>
          <h1 className="text-center">Header</h1>
        </header>
        <nav>
          <ul>
            <li>
              <Link href={{ pathname: '/about' }}>About</Link>
            </li>
            <li>
              <Link href={{ pathname: '/services' }}>Services</Link>
            </li>
            <li>
              <Link href="/contact">Contact</Link>
            </li>
          </ul>
        </nav>
        <hr />
        {children}
        <footer>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
